### ISSUE TITLE
Error when trying to play a song

### ISSUE THREAD

**Issue by js0mmer** [jeffcheema/spotify-but-better#1]
Yo Jeff, every time I try to play a song it crashes and this error is thrown.

```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: options.uri is a required argument
    at Request.init (/home/pi/spotify-but-better/node_modules/request/request.js:231:31)
    at new Request (/home/pi/spotify-but-better/node_modules/request/request.js:127:8)
    at request (/home/pi/spotify-but-better/node_modules/request/index.js:53:10)
    at /home/pi/spotify-but-better/app.js:64:1
    at ChildProcess.exithandler (child_process.js:301:5)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:610:12)
Emitted 'error' event at:
    at Request.init (/home/pi/spotify-but-better/node_modules/request/request.js:231:17)
    at new Request (/home/pi/spotify-but-better/node_modules/request/request.js:127:8)
    [... lines matching original stack trace ...]
    at Pipe._handle.close (net.js:610:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! spotify-but-better@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the spotify-but-better@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-06-05T03_41_10_165Z-debug.log
```

**Comment by js0mmer** [comment]
Fixed after upgrading youtube-dl with pip
